---
sudo: required

language: python

services:
  - docker

install:
  # molecule version >v2.22 required for compatibility with ansible 2.8.x (provided in the used docker image)
  - pip install molecule==2.22
  - pip install docker
script:
  - molecule test
  # TODO test 2nd scenario (multi-node !?)
  #- molecule test --scenario-name xxx

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
